# Mistral Fine-tuning API

Check out the docs: https://docs.mistral.ai/capabilities/finetuning/

In [30]:
# !pip install mistralai pandas
with open("data/secrets/mistral.secret") as f:
    os.environ["MISTRAL_API_KEY"] = f.read()
    api_key = os.environ["MISTRAL_API_KEY"]

## Prepare the dataset

In this example, let’s use the ultrachat_200k dataset. We load a chunk of the data into Pandas Dataframes, split the data into training and validation, and save the data into the required jsonl format for fine-tuning.

In [2]:
import pandas as pd
df = pd.read_parquet('https://huggingface.co/datasets/HuggingFaceH4/ultrachat_200k/resolve/main/data/test_gen-00000-of-00001-3d4cd8309148a71f.parquet')
df

,prompt,prompt_id,messages
24636,Read the passage below and answer the question...,cef194424ecca27ac831d66361160cab4d43dfe297b6df...,[{'content': 'Read the passage below and answe...
10445,Create a comprehensive checklist that includes...,6b8e5334656624d8632490924930514d89f65712bc270d...,[{'content': 'Create a comprehensive checklist...
24929,Can you summarize the controversy surrounding ...,0dffb0a7d5cf4496409b638815d255773b79a618f36a4e...,[{'content': 'Can you summarize the controvers...
6576,Create a set of ten posters that raise awarene...,23bbd05fabd4a47c9485d9e1a7f3589ac67b5367a4044d...,[{'content': 'Create a set of ten posters that...
544,Write clear and concise instructions for how t...,0785d5c6529eaeaa2ae46334592d7b1faa981e7dcae65f...,[{'content': 'Write clear and concise instruct...
...,...,...,...
22134,Can you paraphrase the text about Viktor & Rol...,b9ec7da5bba36dd2cefd2d27db763ebe3ea3c25cb8541f...,[{'content': 'Can you paraphrase the text abou...
23722,Write step-by-step instructions on how to make...,405861102893c1f3fe7d005f9965a5dd658fe5a9f3ebfd...,[{'content': 'Write step-by-step instructions ...
4731,Write a horror story in a gothic style featuri...,fc015c9dd96b45ba4088a95680fbf7d63ae9fabd035d71...,[{'content': 'Write a horror story in a gothic...
15909,Is it possible to obtain a translated version ...,ada9e8528bc772ead5a169af3d66f4e873223f2181239d...,[{'content': 'Is it possible to obtain a trans...
23344,Could you recommend any books or documentaries...,56717025d6efc713d04b0e11c53936a851c2b706d90f5e...,[{'content': 'Could you recommend any books or...

In [25]:
df_train=df[:100]
df_eval=df[100:200]

# df_train.to_json("data/ultrachat_chunk_train.jsonl", orient="records", lines=True)
# df_eval.to_json("data/ultrachat_chunk_eval.jsonl", orient="records", lines=True)
df_eval

,prompt,prompt_id,messages
100,Please write a well-researched and informative...,f93b4789593342c90018ed42fc2f8889cbe00de938ac93...,[{'content': 'Please write a well-researched a...
101,What are the main features offered by air mile...,450104688d133b3b25606cdac0e14cdbc30688fe2b3dd1...,[{'content': 'What are the main features offer...
102,"Let’s go shroomin’, Daddy chortles. of our paw...",4c53368fb13c7d012ad89535856ad6199d118146910150...,"[{'content': 'Let’s go shroomin’, Daddy chortl..."
103,Generate response to the question/instruction ...,badc2b4b1dfec2318648c2c281719df8eaad42b9e248e7...,[{'content': 'Generate response to the questio...
104,Write a 500-word short story in third person n...,d10fb0a6682f0874fc035e988f323b488b3d65f9f988da...,[{'content': 'Write a 500-word short story in ...
...,...,...,...
195,Here is a piece of text: A joke or single reli...,81e09b61ff79bda207c9264c945acb719c41d4201d42ca...,[{'content': 'Here is a piece of text: A joke ...
196,How did the marine engine and boat segments of...,8bf1d793af00ca6df29f9e5d58b897f5093206c4c9fb4a...,[{'content': 'How did the marine engine and bo...
197,Create a comprehensive blog post about time-sa...,ce48ba347744cd10a8215ce2cbf045527cd3b013cccd82...,[{'content': 'Create a comprehensive blog post...
198,Write a well-structured and comprehensive essa...,313d4e18ef7e004f585ec2aa35df2cc4ae15ffd160e8f6...,[{'content': 'Write a well-structured and comp...
199,"From a business perspective, discuss the poten...",c726894b7c4c3ccd83f9e6fcfbc35435fae59816b9e53b...,"[{'content': 'From a business perspective, dis..."

## Reformat dataset
If you upload this ultrachat_chunk_train.jsonl to Mistral API, you might encounter an error message “Invalid file format” due to data formatting issues. To reformat the data into the correct format, you can download the reformat_dataset.py script and use it to validate and reformat both the training and evaluation data:

In [18]:
# download the validation and reformat script
# !wget https://raw.githubusercontent.com/mistralai/mistral-finetune/main/utils/reformat_data.py

In [26]:
# validate and reformat the training data
# !python reformat_data.py data/ultrachat_chunk_train.jsonl

In [27]:
# validate the reformat the eval data
# !python reformat_data.py data/ultrachat_chunk_eval.jsonl

In [28]:
df_train.iloc[55]['messages']

array([{'content': 'Write a plot outline for a fast-paced thriller in which an experienced spy races against time to prevent a group of terrorists from carrying out a devastating attack. Ensure that your story features plenty of heart-stopping action, high-tech espionage, and unexpected plot twists to keep readers on the edge of their seats from beginning to end. Consider incorporating elements of political intrigue, international espionage, and personal stake in the hero’s success to create a truly immersive and engaging reading experience.', 'role': 'user'},
       {'content': 'Title: The Final Countdown\n\nAct 1:\n- Introduction of protagonist, John Steele, a highly skilled and experienced spy, who is called into action once again\n- A group of terrorists led by a mysterious mastermind, known only as "The Shadow", plan to carry out a devastating attack on an unknown location and Steele is tasked with preventing it\n- Steele discovers that the target of the attack is a major metropolis, which will result in the loss of millions of lives\n- Steele appeals to his former colleagues at the intelligence agency for assistance, but they are hesitant to believe his theories due to Steele\'s history of going rogue in the past\n- Steele must rely on his instincts and his own resources to piece together the clues and unearth the terrorists\' plan\n\nAct 2:\n- Steele discovers that the terrorists have obtained a highly advanced weapon, capable of destroying entire cities with a single blast\n- Steele races against time to uncover the location of the weapon and the identity of The Shadow\n- The stakes are raised when it is revealed that one of Steele\'s loved ones is also a target of the terrorists\n- Steele must navigate the dangerous world of international espionage and political intrigue, while also eluding the intelligence agencies who are still trying to apprehend him\n- The clock is ticking as Steele launches a daring mission to stop the terrorists and prevent the attack before it\'s too late\n\nAct 3:\n- Steele\'s daring mission results in a face-off with The Shadow and his team, resulting in a heart-stopping battle between the two sides\n- Just when it seems like Steele has triumphed over the terrorists, a shocking twist is revealed\n- Steele must fight against all odds to stop the terrorists from deploying the weapon and saving the lives of millions of innocent people\n- In a thrilling and explosive conclusion, Steele saves the day and eliminates the threat of the terrorist attack once and for all, but not without suffering a personal loss\n- Steele\'s success, however, comes at a heavy price, and he must reconcile with the consequences of his actions and the sacrifices he had to make. \n\nEpilogue:\n- The intelligence agencies begrudgingly acknowledge Steele\'s heroism and skill, offering him a clean slate and the opportunity to rejoin their ranks\n- Steele, however, decides to retire from the spy game and go off the grid, still haunted by the memories of his past actions\n- The story ends with a hint that Steele may be called into action once more, leaving readers on the edge of their seats and eager for more.', 'role': 'assistant'},
       {'content': 'That plot outline sounds great! Can you add some more high-tech espionage elements to the story to make it more exciting?', 'role': 'user'},
       {'content': 'Absolutely! Here\'s an updated plot outline with more high-tech espionage elements:\n\nTitle: The Final Countdown\n\nAct 1:\n- Introduction of protagonist, John Steele, a highly skilled and experienced spy, who is called into action once again\n- A group of terrorists led by a mysterious mastermind, known only as "The Shadow", plan to carry out a devastating attack on an unknown location and Steele is tasked with preventing it\n- Steele discovers that the target of the attack is a major metropolis, which will result in the loss of millions of lives\n- Steele must rely on his expertise in high-tech espionage to track down the terrorists and uncover their plans\n- He uses cutting-edge gadgets and technology, working alongside a team of fellow spies with complementary skills and resources to identify the terrorists’ locations and infiltrate their communication networks.\n\nAct 2:\n- Steele uses his mastery of surveillance techniques and his familiarity with state-of-the-art intelligence resources to identify the terrorists\' base of operations\n- He faces numerous obstacles such as encrypted communication codes and sophisticated cybersecurity, which only heighten the challenge in his pursuit of the Shadow, that stays one step ahead of Steele.\n- The stakes are raised when it is revealed that one of Steele\'s trusted colleagues may be working with the terrorists or could be used as a pawn.\n- He launches a daring cyber-attack to disable the terrorists\' weapon, evading their high-tech security and staying one step ahead of the Shadow\n\nAct 3:\n- Steele engages in a high-octane final showdown with the terrorists in which he utilizes his expert hacking abilities to disable their weapon and "disappear"\n- Steele\'s cunning and quick thinking save the day, but just when he thinks it\'s over, he discovers a second catastrophic plot that could result in even greater loss of life.\n- Racing against time, and relying on his top-notch tech skills, Steele and his team pull off an impossible mission, ultimately defeating the Shadow in a suspenseful, high-stakes conclusion.\n- As the threat subsides, Steele\'s colleagues and counterparts acknowledge his exceptional skills - skills that he may need again in the future as the world faces new dangers.\n\nEpilogue:\n- Steele decides to take a break and reflect on his life, pondering if he is ready for his next mission.\n- The final scene leaves readers with a cryptic message from an unknown sender, hinting at a new and more dangerous mission in the future, leading readers to speculate about a sequel or next installment.', 'role': 'assistant'},
       {'content': 'Wow, I love the updated plot outline! Can we add more scenes with high-speed chases and epic fight sequences? I want to make sure the story is action-packed from beginning to end.', 'role': 'user'},
       {'content': 'Sure! Here\'s an updated plot outline with more high-speed chases and epic fight sequences:\n\nTitle: The Final Countdown\n\nAct 1:\n- Introduction of protagonist, John Steele, a highly skilled and experienced spy, who is called into action once again\n- A group of terrorists led by a mysterious mastermind, known only as "The Shadow", plan to carry out a devastating attack on an unknown location and Steele is tasked with preventing it\n- Steele discovers that the target of the attack is a major metropolis, which will result in the loss of millions of lives\n- Steele must rely on his expertise in high-tech espionage to track down the terrorists and uncover their plans, but his pursuit leads to multi-city chases and heavy fight sequences in crowded places.\n- The terrorist attacks become more frequent, and it\'s up to Steele to apprehend the Shadow before they strike again.\n\nAct 2:\n- Steele receives intelligence on terrorist plans, which leads to a pursuit that takes the reader on an action-packed ride. From chasing terrorists in a busy market to combat in a high-security building, no distances too far or too dangerous for Steele and his team.\n- With the help of his team\'s sophisticated gadgets and advanced technology, Steele races through the city streets, engaging in thrilling high-speed chases that leave readers on the edge of their seats.\n- As time runs out and the stakes soar, Steele engages in epic hand-to-hand combat and shootouts as he fights to gain the upper hand against the terrorists.\n- The terrorists\' next move threatens to destroy the city and its landmarks. Steele must race against the clock and execute high-risk main mission with strict adherence to precision and accuracy to disarm the explosives without triggering a city-wide catastrophe.\n\nAct 3:\n- With the Shadow\'s identity finally revealed, Steele engages in one final epic showdown in a highly secured district. The stakes are upped when his teammates are caught in the crossfire.\n- Steele navigates challenging environments, making every move with precision in a bid to save his team and the city. In a highly sophisticated, high-tech final battle that is worthy of a Hollywood movie, Steele takes down the Shadow in a nerve-wrecking fight sequence that requires him to use all his highly honed skills.\n- The story concludes with Steele saving the city and his team. For him, there is casualties to mourn, reflection on his life and contemplation of his next adventure.\n\nEpilogue:\n- Steele reflects on the events, draws lessons from the fight, and moves on to his next mission, whenever that\'ll be. The story ends with a foreboding message that suggests he will soon need to suit up again for another thrilling adventure.', 'role': 'assistant'},
       {'content': 'This plot outline is really amazing! Can you add more plot twists and unexpected turns to make it even more thrilling? I want to be surprised every step of the way!', 'role': 'user'}],
      dtype=object)

## Upload dataset

In [32]:
from mistralai import Mistral
import os

api_key = os.environ["MISTRAL_API_KEY"]

client = Mistral(api_key=api_key)

ultrachat_chunk_train = client.files.upload(file={
    "file_name": "data/ultrachat_chunk_train.jsonl",
    "content": open("data/ultrachat_chunk_train.jsonl", "rb"),
})
ultrachat_chunk_eval = client.files.upload(file={
    "file_name": "data/ultrachat_chunk_eval.jsonl",
    "content": open("data/ultrachat_chunk_eval.jsonl", "rb"),
})

In [33]:
import json
def pprint(obj):
    print(json.dumps(obj.dict(), indent=4))

In [34]:
pprint(ultrachat_chunk_train)

{
    "id": "79eeb1bd-ce96-477c-8f37-80bfe0ab03f9",
    "object": "file",
    "bytes": null,
    "created_at": 1760922442,
    "filename": "ultrachat_chunk_train.jsonl",
    "purpose": "fine-tune",
    "sample_type": "instruct",
    "source": "upload",
    "num_lines": 100,
    "mimetype": "application/jsonl",
    "signature": "fb43e507a74da1c9"
}

C:\Users\conta\AppData\Local\Temp\ipykernel_33524\3084144206.py:3: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
  print(json.dumps(obj.dict(), indent=4))

In [35]:
pprint(ultrachat_chunk_eval)

{
    "id": "19ac51de-b3da-4c6b-8786-d27c24d9eacc",
    "object": "file",
    "bytes": null,
    "created_at": 1760922459,
    "filename": "ultrachat_chunk_eval.jsonl",
    "purpose": "fine-tune",
    "sample_type": "instruct",
    "source": "upload",
    "num_lines": 100,
    "mimetype": "application/jsonl",
    "signature": "973b174524a0f4d9"
}

C:\Users\conta\AppData\Local\Temp\ipykernel_33524\3084144206.py:3: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
  print(json.dumps(obj.dict(), indent=4))

## Create a fine-tuning job

In [ ]:
created_jobs = client.fine_tuning.jobs.create(
    model="open-mistral-7b",
    training_files=[{"file_id": ultrachat_chunk_train.id, "weight": 1}],
    validation_files=[ultrachat_chunk_eval.id],
    hyperparameters={
    "training_steps": 2,
    "learning_rate":0.0001
    },
    auto_start=True
)
created_jobs

JobOut(id='20178c3c-d75b-428e-b20d-7d39aa2b7468', auto_start=True, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=None, fim_ratio=None), model='open-mistral-7b', status='QUEUED', job_type='FT', created_at=1721405548, modified_at=1721405548, training_files=['ec5af16a-77fe-4e14-ad09-47ead2848ce6'], validation_files=['d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4'], OBJECT='job', fine_tuned_model=None, suffix=None, integrations=[], trained_tokens=None, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None))

In [ ]:
pprint(created_jobs)

{
    "id": "2c002adb-12be-4a5d-a3ef-baacf9025be9",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": null,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "QUEUED",
    "job_type": "FT",
    "created_at": 1721405164,
    "modified_at": 1721405164,
    "training_files": [
        "da7305f6-d649-4fe2-8132-d6f17c7c8141"
    ],
    "validation_files": [
        "f33adf06-8d79-420f-8722-d988cd60fbd6"
    ],
    "fine_tuned_model": null,
    "suffix": null,
    "integrations": [],
    "trained_tokens": null,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": null,
        "cost": null,
        "cost_currency": null,
        "train_tokens_per_step": null,
        "train_tokens": null,
        "data_tokens": null,
        "estimated_start_time": null
    }
}

In [ ]:
jobs = client.fine_tuning.jobs.list()
print(jobs)

total=32 data=[JobOut(id='20178c3c-d75b-428e-b20d-7d39aa2b7468', auto_start=True, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=0.0431941570306258, fim_ratio=None), model='open-mistral-7b', status='RUNNING', job_type='FT', created_at=1721405548, modified_at=1721405549, training_files=['ec5af16a-77fe-4e14-ad09-47ead2848ce6'], validation_files=['d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4'], OBJECT='job', fine_tuned_model=None, suffix=None, integrations=[], trained_tokens=None, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=120, cost=2.6214, cost_currency='USD', train_tokens_per_step=131072, train_tokens=1310720, data_tokens=30344845, estimated_start_time=None)), JobOut(id='98cbe43b-61e5-47a8-a5fb-57f6d82abc0a', auto_start=True, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=0.0431941570306258, fim_ratio=None), model='open-mistral-7b', status='RUNNING', job_type='FT', created_at=1721405463, modified_at=1721405466, training_files=['71664e51-eae4-4c5b-9007-2c4586265609'], validation_files=['6c09517c-32d9-465c-8e4b-4496d1401ba0'], OBJECT='job', fine_tuned_model=None, suffix=None, integrations=[], trained_tokens=None, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=120, cost=2.6214, cost_currency='USD', train_tokens_per_step=131072, train_tokens=1310720, data_tokens=30344845, estimated_start_time=None)), JobOut(id='baf7cb65-5ab6-4cdd-a4c6-a6f90c18cd7b', auto_start=True, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=0.0431941570306258, fim_ratio=None), model='open-mistral-7b', status='SUCCESS', job_type='FT', created_at=1721396928, modified_at=1721397062, training_files=['96d5e16c-d701-455c-8f76-82054d005325'], validation_files=['cfc6dd29-f82e-48c0-8153-59e2313600c8'], OBJECT='job', fine_tuned_model='ft:open-mistral-7b:b6e34a5e:20240719:baf7cb65', suffix=None, integrations=[], trained_tokens=1310720, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=100, cost=2.6214, cost_currency='USD', train_tokens_per_step=131072, train_tokens=1310720, data_tokens=30344845, estimated_start_time=None)), JobOut(id='7d82092d-a827-4943-9361-b321c6a3809c', auto_start=False, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=0.0431941570306258, fim_ratio=None), model='open-mistral-7b', status='VALIDATED', job_type='FT', created_at=1721396750, modified_at=1721396751, training_files=['96d5e16c-d701-455c-8f76-82054d005325'], validation_files=['cfc6dd29-f82e-48c0-8153-59e2313600c8'], OBJECT='job', fine_tuned_model=None, suffix=None, integrations=[], trained_tokens=None, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=100, cost=2.6214, cost_currency='USD', train_tokens_per_step=131072, train_tokens=1310720, data_tokens=30344845, estimated_start_time=None)), JobOut(id='1d69c7fc-fba8-40ad-92d1-3811b708cde1', auto_start=True, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=0.0431941570306258, fim_ratio=None), model='open-mistral-7b', status='SUCCESS', job_type='FT', created_at=1721396736, modified_at=1721396871, training_files=['96d5e16c-d701-455c-8f76-82054d005325'], validation_files=['cfc6dd29-f82e-48c0-8153-59e2313600c8'], OBJECT='job', fine_tuned_model='ft:open-mistral-7b:b6e34a5e:20240719:1d69c7fc', suffix=None, integrations=[], trained_tokens=1310720, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=100, cost=2.6214, cost_currency='USD', train_tokens_per_step=131072, train_tokens=1310720, data_tokens=30344845, estimated_start_time=None)), JobOut(id='64192a7e-b09a-4917-8760-015f90073a7b', auto_start=False, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=0.0431941570306258, fim_ratio=None), model='open-mistral-7b', status='VALIDATED', job_type='FT', created_at=1721396729, modified_at=1721396730, training_files=['96d5e16c-d701-455c-8f76-82054d005325'], validation_files=['cfc6dd29-f82e-48c0-8153-59e2313600c8'], OBJECT='job', fine_tuned_model=None, suffix=None, integrations=[], trained_tokens=None, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=100, cost=2.6214, cost_currency='USD', train_tokens_per_step=131072, train_tokens=1310720, data_tokens=30344845, estimated_start_time=None)), JobOut(id='adc708bd-877a-4201-bef1-16a1f1d93967', auto_start=True, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=0.0431941570306258, fim_ratio=None), model='open-mistral-7b', status='SUCCESS', job_type='FT', created_at=1721396580, modified_at=1721396718, training_files=['96d5e16c-d701-455c-8f76-82054d005325'], validation_files=['cfc6dd29-f82e-48c0-8153-59e2313600c8'], OBJECT='job', fine_tuned_model='ft:open-mistral-7b:b6e34a5e:20240719:adc708bd', suffix=None, integrations=[], trained_tokens=1310720, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=100, cost=2.6214, cost_currency='USD', train_tokens_per_step=131072, train_tokens=1310720, data_tokens=30344845, estimated_start_time=None)), JobOut(id='372926dc-6cea-4198-8234-bd9c1856a2e5', auto_start=True, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=0.0431941570306258, fim_ratio=None), model='open-mistral-7b', status='SUCCESS', job_type='FT', created_at=1721396234, modified_at=1721396369, training_files=['96d5e16c-d701-455c-8f76-82054d005325'], validation_files=['cfc6dd29-f82e-48c0-8153-59e2313600c8'], OBJECT='job', fine_tuned_model='ft:open-mistral-7b:b6e34a5e:20240719:372926dc', suffix=None, integrations=[], trained_tokens=1310720, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=140, cost=2.6214, cost_currency='USD', train_tokens_per_step=131072, train_tokens=1310720, data_tokens=30344845, estimated_start_time=None)), JobOut(id='bdfa52a5-3d66-4c51-bf37-b4ec6e4fa612', auto_start=True, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=0.0431941570306258, fim_ratio=None), model='open-mistral-7b', status='SUCCESS', job_type='FT', created_at=1721383368, modified_at=1721383502, training_files=['962f783d-d38a-46e2-aa7a-8826bf1a42f1'], validation_files=['1d6dbb85-09b6-4962-94f6-ae51f2353733'], OBJECT='job', fine_tuned_model='ft:open-mistral-7b:b6e34a5e:20240719:bdfa52a5', suffix=None, integrations=[], trained_tokens=1310720, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=210, cost=2.6214, cost_currency='USD', train_tokens_per_step=131072, train_tokens=1310720, data_tokens=30344845, estimated_start_time=None)), JobOut(id='ded06fc3-7cf9-4753-a157-c2c3f9c0103b', auto_start=True, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=None, fim_ratio=None), model='open-mistral-7b', status='SUCCESS', job_type='FT', created_at=1720629436, modified_at=1720629567, training_files=['2f1e95bb-49cb-4998-9a2c-57a6093390ad'], validation_files=['dfeaa63b-55c5-4850-afd5-61ffebf26782'], OBJECT='job', fine_tuned_model='ft:open-mistral-7b:b6e34a5e:20240710:ded06fc3', suffix=None, integrations=[], trained_tokens=1310720, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='d1587e39-eb2a-43ac-9f6b-4fa4d0e45c31', auto_start=True, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=None, fim_ratio=None), model='open-mistral-7b', status='SUCCESS', job_type='FT', created_at=1720629167, modified_at=1720629288, training_files=['93b01e13-1834-4a8b-b60a-5538d59b2c93'], validation_files=['2e1eb79d-388f-4c03-acfa-09b4bad51a91'], OBJECT='job', fine_tuned_model='ft:open-mistral-7b:b6e34a5e:20240710:d1587e39', suffix=None, integrations=[], trained_tokens=1310720, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='e89017e4-d038-4056-a869-73ee9e87c79e', auto_start=True, hyperparameters=TrainingParameters(training_steps=400, learning_rate=0.0003, epochs=None, fim_ratio=None), model='mistral-small-latest', status='SUCCESS', job_type='FT', created_at=1717576147, modified_at=1717593291, training_files=['8609ba12-353f-4277-87c8-0e1f7b6f72ce'], validation_files=['0c5f525a-8dce-4c70-abfd-6bff1ec8e0c0'], OBJECT='job', fine_tuned_model='ft:mistral-small-latest:b6e34a5e:20240605:e89017e4', suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='economist_style_guide_v8')], trained_tokens=52428800, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='3912b6ef-d2da-46b0-946f-56c243b8146f', auto_start=True, hyperparameters=TrainingParameters(training_steps=200, learning_rate=0.0003, epochs=None, fim_ratio=None), model='mistral-small-latest', status='SUCCESS', job_type='FT', created_at=1717576026, modified_at=1717584730, training_files=['8609ba12-353f-4277-87c8-0e1f7b6f72ce'], validation_files=['0c5f525a-8dce-4c70-abfd-6bff1ec8e0c0'], OBJECT='job', fine_tuned_model='ft:mistral-small-latest:b6e34a5e:20240605:3912b6ef', suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='economist_style_guide_v7')], trained_tokens=26214400, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='7d0c9b8c-d3c7-4890-9788-ea12b917cb46', auto_start=True, hyperparameters=TrainingParameters(training_steps=1500, learning_rate=7.5e-05, epochs=None, fim_ratio=None), model='mistral-small-latest', status='FAILED', job_type='FT', created_at=1717575567, modified_at=1717575890, training_files=['8609ba12-353f-4277-87c8-0e1f7b6f72ce'], validation_files=['0c5f525a-8dce-4c70-abfd-6bff1ec8e0c0'], OBJECT='job', fine_tuned_model=None, suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='economist_style_guide_v6')], trained_tokens=None, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='1d50c69f-4ed5-4888-a05d-cea08e8a1e49', auto_start=True, hyperparameters=TrainingParameters(training_steps=800, learning_rate=7.5e-05, epochs=None, fim_ratio=None), model='mistral-small-latest', status='FAILED', job_type='FT', created_at=1717575373, modified_at=1717575868, training_files=['8609ba12-353f-4277-87c8-0e1f7b6f72ce'], validation_files=['0c5f525a-8dce-4c70-abfd-6bff1ec8e0c0'], OBJECT='job', fine_tuned_model=None, suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='economist_style_guide_v5')], trained_tokens=None, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='56578b71-9952-445e-a1c4-a77e8970a396', auto_start=True, hyperparameters=TrainingParameters(training_steps=1000, learning_rate=7.5e-05, epochs=None, fim_ratio=None), model='mistral-small-latest', status='SUCCESS', job_type='FT', created_at=1717513741, modified_at=1717519351, training_files=['ab8a0a0e-699d-4084-a766-afd681c3e690'], validation_files=['9e48568e-0f51-48d0-bc87-dc45aaba6f4e'], OBJECT='job', fine_tuned_model='ft:mistral-small-latest:b6e34a5e:20240604:56578b71', suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='economist_style_guide_v4')], trained_tokens=16384000, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='ee1ab18b-5333-4bbd-b329-7e3ab6e0112f', auto_start=True, hyperparameters=TrainingParameters(training_steps=1000, learning_rate=7.5e-05, epochs=None, fim_ratio=None), model='mistral-small-latest', status='SUCCESS', job_type='FT', created_at=1717513723, modified_at=1717519428, training_files=['ab8a0a0e-699d-4084-a766-afd681c3e690'], validation_files=['9e48568e-0f51-48d0-bc87-dc45aaba6f4e'], OBJECT='job', fine_tuned_model='ft:mistral-small-latest:b6e34a5e:20240604:ee1ab18b', suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='economist_style_guide_v4')], trained_tokens=16384000, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='068ac05d-c6a6-445d-af61-a32417b846b5', auto_start=True, hyperparameters=TrainingParameters(training_steps=1500, learning_rate=0.0001, epochs=None, fim_ratio=None), model='mistral-small-latest', status='FAILED', job_type='FT', created_at=1717513568, modified_at=1717513655, training_files=['ab8a0a0e-699d-4084-a766-afd681c3e690'], validation_files=['9e48568e-0f51-48d0-bc87-dc45aaba6f4e'], OBJECT='job', fine_tuned_model=None, suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='economist_style_guide_v3')], trained_tokens=None, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='06f94d85-fb0f-443b-a4c3-9893ef4f8d41', auto_start=True, hyperparameters=TrainingParameters(training_steps=1500, learning_rate=0.0001, epochs=None, fim_ratio=None), model='mistral-small-latest', status='SUCCESS', job_type='FT', created_at=1717498861, modified_at=1717507124, training_files=['d6a724d5-4792-444a-8aba-c412da7a0a1c'], validation_files=['3e33c90e-6271-4307-b033-a7b72262957b'], OBJECT='job', fine_tuned_model='ft:mistral-small-latest:b6e34a5e:20240604:06f94d85', suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='economist_style_guide_v3')], trained_tokens=24576000, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='7abfcf8f-6e99-486b-adc8-140cdc931874', auto_start=True, hyperparameters=TrainingParameters(training_steps=1500, learning_rate=0.0003, epochs=None, fim_ratio=None), model='mistral-small-latest', status='SUCCESS', job_type='FT', created_at=1717493002, modified_at=1717501386, training_files=['d6a724d5-4792-444a-8aba-c412da7a0a1c'], validation_files=['3e33c90e-6271-4307-b033-a7b72262957b'], OBJECT='job', fine_tuned_model='ft:mistral-small-latest:b6e34a5e:20240604:7abfcf8f', suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='economist_style_guide_v2')], trained_tokens=24576000, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='9967f1a4-c985-4b29-acb8-05b17247ae1f', auto_start=True, hyperparameters=TrainingParameters(training_steps=1000, learning_rate=0.0001, epochs=None, fim_ratio=None), model='mistral-small-latest', status='SUCCESS', job_type='FT', created_at=1717453634, modified_at=1717459021, training_files=['502d7435-c6a7-4245-b6c5-33cd5eaf1fc5'], validation_files=['218f74d3-5961-460b-8452-59adc037231c'], OBJECT='job', fine_tuned_model=None, suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='economist_style_guide_v1')], trained_tokens=16384000, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='adf036e3-69af-4762-bcd5-73b5226c2c64', auto_start=True, hyperparameters=TrainingParameters(training_steps=1000, learning_rate=0.0005, epochs=None, fim_ratio=None), model='open-mistral-7b', status='SUCCESS', job_type='FT', created_at=1717154159, modified_at=1717164477, training_files=['6438efb1-4ebc-4802-b67b-2f0069c5e4ec'], validation_files=['467c19ae-6000-4148-8cae-b8d42aa6068a'], OBJECT='job', fine_tuned_model='ft:open-mistral-7b:b6e34a5e:20240531:adf036e3', suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='rapper_v0')], trained_tokens=32768000, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='15a987eb-9bd6-479c-82bb-3a2582d5d0f2', auto_start=True, hyperparameters=TrainingParameters(training_steps=1000, learning_rate=0.0005, epochs=None, fim_ratio=None), model='open-mistral-7b', status='SUCCESS', job_type='FT', created_at=1717153851, modified_at=1717160771, training_files=['4a9a79b0-609c-4f94-b54e-82d0f9ef6037'], validation_files=['dd70766f-6d25-4e6f-a045-8753e9dfd896'], OBJECT='job', fine_tuned_model='ft:open-mistral-7b:b6e34a5e:20240531:15a987eb', suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='socrates_v0')], trained_tokens=32768000, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='00428354-ed52-450f-a299-0b47935d3ceb', auto_start=True, hyperparameters=TrainingParameters(training_steps=1000, learning_rate=0.0005, epochs=None, fim_ratio=None), model='mistral-small-latest', status='SUCCESS', job_type='FT', created_at=1717153185, modified_at=1717171939, training_files=['d1e4d2fc-c6ba-46ce-a070-0270b7a30012'], validation_files=['74884504-4a67-4806-adab-36a15d5e547a'], OBJECT='job', fine_tuned_model='ft:mistral-small-latest:b6e34a5e:20240531:00428354', suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='call_assistant_v0')], trained_tokens=16384000, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='50d006d4-3983-45ad-a071-56e070624eef', auto_start=True, hyperparameters=TrainingParameters(training_steps=1000, learning_rate=0.0005, epochs=None, fim_ratio=None), model='open-mistral-7b', status='SUCCESS', job_type='FT', created_at=1717153161, modified_at=1717158631, training_files=['d1e4d2fc-c6ba-46ce-a070-0270b7a30012'], validation_files=['74884504-4a67-4806-adab-36a15d5e547a'], OBJECT='job', fine_tuned_model='ft:open-mistral-7b:b6e34a5e:20240531:50d006d4', suffix=None, integrations=[WandbIntegrationOut(project='test_api', TYPE='wandb', name=None, run_name='call_assistant_v0')], trained_tokens=32768000, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=None, cost=None, cost_currency=None, train_tokens_per_step=None, train_tokens=None, data_tokens=None, estimated_start_time=None)), JobOut(id='4ffddbce-caca-4dda-b49b-c1868213d141', auto_start=True, hyperparameters=TrainingParameters(training_steps=1000, learning_rate=0.0005, epochs=None, fim_ratio=None), model='open-mistral-7b', status='SUCCESS', job_type='FT', created_at=1717150637, modified_at=1717154822, training_files=['935a5891-500f-40d8-897d-bf917fcf9d51'], validation_files=['898df146-9f3b-48d3-9a4a-1740cff98748'], OBJECT='job', fine_tuned_model='ft:open-mistral-7b:b6e34a5e:20240531:4ffdd

In [ ]:
retrieved_jobs = client.fine_tuning.jobs.get(job_id = created_jobs.id)
retrieved_jobs

DetailedJobOut(id='20178c3c-d75b-428e-b20d-7d39aa2b7468', auto_start=True, hyperparameters=TrainingParameters(training_steps=10, learning_rate=0.0001, epochs=0.0431941570306258, fim_ratio=None), model='open-mistral-7b', status='RUNNING', job_type='FT', created_at=1721405548, modified_at=1721405549, training_files=['ec5af16a-77fe-4e14-ad09-47ead2848ce6'], validation_files=['d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4'], OBJECT='job', fine_tuned_model=None, suffix=None, integrations=[], trained_tokens=None, repositories=[], metadata=JobMetadataOut(expected_duration_seconds=120, cost=2.6214, cost_currency='USD', train_tokens_per_step=131072, train_tokens=1310720, data_tokens=30344845, estimated_start_time=None), events=[EventOut(name='status-updated', created_at=1721405549, data=Unset()), EventOut(name='status-updated', created_at=1721405549, data=Unset()), EventOut(name='status-updated', created_at=1721405549, data=Unset()), EventOut(name='status-updated', created_at=1721405548, data=Unset()), EventOut(name='status-updated', created_at=1721405548, data=Unset())], checkpoints=[])

In [ ]:
import time

retrieved_job = client.fine_tuning.jobs.get(job_id = created_jobs.id)
while retrieved_job.status in ["RUNNING", "QUEUED"]:
    retrieved_job = client.fine_tuning.jobs.get(job_id = created_jobs.id)
    pprint(retrieved_job)
    print(f"Job is {retrieved_job.status}, waiting 10 seconds")
    time.sleep(10)

{
    "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": 0.0431941570306258,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "RUNNING",
    "job_type": "FT",
    "created_at": 1721405548,
    "modified_at": 1721405549,
    "training_files": [
        "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
    ],
    "validation_files": [
        "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
    ],
    "fine_tuned_model": null,
    "suffix": null,
    "integrations": [],
    "trained_tokens": null,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": 120,
        "cost": 2.6214,
        "cost_currency": "USD",
        "train_tokens_per_step": 131072,
        "train_tokens": 1310720,
        "data_tokens": 30344845,
        "estimated_start_time": null
    },
    "events": [
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        }
    ],
    "checkpoints": []
}
Job is RUNNING, waiting 10 seconds
{
    "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": 0.0431941570306258,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "RUNNING",
    "job_type": "FT",
    "created_at": 1721405548,
    "modified_at": 1721405549,
    "training_files": [
        "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
    ],
    "validation_files": [
        "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
    ],
    "fine_tuned_model": null,
    "suffix": null,
    "integrations": [],
    "trained_tokens": null,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": 120,
        "cost": 2.6214,
        "cost_currency": "USD",
        "train_tokens_per_step": 131072,
        "train_tokens": 1310720,
        "data_tokens": 30344845,
        "estimated_start_time": null
    },
    "events": [
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        }
    ],
    "checkpoints": []
}
Job is RUNNING, waiting 10 seconds
{
    "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": 0.0431941570306258,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "RUNNING",
    "job_type": "FT",
    "created_at": 1721405548,
    "modified_at": 1721405549,
    "training_files": [
        "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
    ],
    "validation_files": [
        "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
    ],
    "fine_tuned_model": null,
    "suffix": null,
    "integrations": [],
    "trained_tokens": null,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": 120,
        "cost": 2.6214,
        "cost_currency": "USD",
        "train_tokens_per_step": 131072,
        "train_tokens": 1310720,
        "data_tokens": 30344845,
        "estimated_start_time": null
    },
    "events": [
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        }
    ],
    "checkpoints": []
}
Job is RUNNING, waiting 10 seconds
{
    "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": 0.0431941570306258,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "RUNNING",
    "job_type": "FT",
    "created_at": 1721405548,
    "modified_at": 1721405549,
    "training_files": [
        "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
    ],
    "validation_files": [
        "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
    ],
    "fine_tuned_model": null,
    "suffix": null,
    "integrations": [],
    "trained_tokens": null,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": 120,
        "cost": 2.6214,
        "cost_currency": "USD",
        "train_tokens_per_step": 131072,
        "train_tokens": 1310720,
        "data_tokens": 30344845,
        "estimated_start_time": null
    },
    "events": [
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        }
    ],
    "checkpoints": []
}
Job is RUNNING, waiting 10 seconds
{
    "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": 0.0431941570306258,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "RUNNING",
    "job_type": "FT",
    "created_at": 1721405548,
    "modified_at": 1721405549,
    "training_files": [
        "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
    ],
    "validation_files": [
        "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
    ],
    "fine_tuned_model": null,
    "suffix": null,
    "integrations": [],
    "trained_tokens": null,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": 120,
        "cost": 2.6214,
        "cost_currency": "USD",
        "train_tokens_per_step": 131072,
        "train_tokens": 1310720,
        "data_tokens": 30344845,
        "estimated_start_time": null
    },
    "events": [
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        }
    ],
    "checkpoints": []
}
Job is RUNNING, waiting 10 seconds
{
    "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": 0.0431941570306258,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "RUNNING",
    "job_type": "FT",
    "created_at": 1721405548,
    "modified_at": 1721405549,
    "training_files": [
        "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
    ],
    "validation_files": [
        "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
    ],
    "fine_tuned_model": null,
    "suffix": null,
    "integrations": [],
    "trained_tokens": null,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": 120,
        "cost": 2.6214,
        "cost_currency": "USD",
        "train_tokens_per_step": 131072,
        "train_tokens": 1310720,
        "data_tokens": 30344845,
        "estimated_start_time": null
    },
    "events": [
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        }
    ],
    "checkpoints": []
}
Job is RUNNING, waiting 10 seconds
{
    "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": 0.0431941570306258,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "RUNNING",
    "job_type": "FT",
    "created_at": 1721405548,
    "modified_at": 1721405549,
    "training_files": [
        "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
    ],
    "validation_files": [
        "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
    ],
    "fine_tuned_model": null,
    "suffix": null,
    "integrations": [],
    "trained_tokens": null,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": 120,
        "cost": 2.6214,
        "cost_currency": "USD",
        "train_tokens_per_step": 131072,
        "train_tokens": 1310720,
        "data_tokens": 30344845,
        "estimated_start_time": null
    },
    "events": [
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        }
    ],
    "checkpoints": [
        {
            "metrics": {
                "train_loss": 0.851776,
                "valid_loss": 0.92623,
                "valid_mean_token_accuracy": 1.900304
            },
            "step_number": 10,
            "created_at": 1721405660
        }
    ]
}
Job is RUNNING, waiting 10 seconds
{
    "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": 0.0431941570306258,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "RUNNING",
    "job_type": "FT",
    "created_at": 1721405548,
    "modified_at": 1721405549,
    "training_files": [
        "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
    ],
    "validation_files": [
        "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
    ],
    "fine_tuned_model": null,
    "suffix": null,
    "integrations": [],
    "trained_tokens": null,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": 120,
        "cost": 2.6214,
        "cost_currency": "USD",
        "train_tokens_per_step": 131072,
        "train_tokens": 1310720,
        "data_tokens": 30344845,
        "estimated_start_time": null
    },
    "events": [
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        }
    ],
    "checkpoints": [
        {
            "metrics": {
                "train_loss": 0.851776,
                "valid_loss": 0.92623,
                "valid_mean_token_accuracy": 1.900304
            },
            "step_number": 10,
            "created_at": 1721405660
        }
    ]
}
Job is RUNNING, waiting 10 seconds
{
    "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": 0.0431941570306258,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "RUNNING",
    "job_type": "FT",
    "created_at": 1721405548,
    "modified_at": 1721405549,
    "training_files": [
        "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
    ],
    "validation_files": [
        "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
    ],
    "fine_tuned_model": null,
    "suffix": null,
    "integrations": [],
    "trained_tokens": null,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": 120,
        "cost": 2.6214,
        "cost_currency": "USD",
        "train_tokens_per_step": 131072,
        "train_tokens": 1310720,
        "data_tokens": 30344845,
        "estimated_start_time": null
    },
    "events": [
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        }
    ],
    "checkpoints": [
        {
            "metrics": {
                "train_loss": 0.851776,
                "valid_loss": 0.92623,
                "valid_mean_token_accuracy": 1.900304
            },
            "step_number": 10,
            "created_at": 1721405660
        }
    ]
}
Job is RUNNING, waiting 10 seconds
{
    "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": 0.0431941570306258,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "SUCCESS",
    "job_type": "FT",
    "created_at": 1721405548,
    "modified_at": 1721405693,
    "training_files": [
        "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
    ],
    "validation_files": [
        "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
    ],
    "fine_tuned_model": "ft:open-mistral-7b:b6e34a5e:20240719:20178c3c",
    "suffix": null,
    "integrations": [],
    "trained_tokens": 1310720,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": 120,
        "cost": 2.6214,
        "cost_currency": "USD",
        "train_tokens_per_step": 131072,
        "train_tokens": 1310720,
        "data_tokens": 30344845,
        "estimated_start_time": null
    },
    "events": [
        {
            "name": "status-updated",
            "created_at": 1721405693
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        }
    ],
    "checkpoints": [
        {
            "metrics": {
                "train_loss": 0.851776,
                "valid_loss": 0.92623,
                "valid_mean_token_accuracy": 1.900304
            },
            "step_number": 10,
            "created_at": 1721405660
        }
    ]
}
Job is SUCCESS, waiting 10 seconds

In [ ]:
# List jobs
jobs = client.fine_tuning.jobs.list()
pprint(jobs)

{
    "total": 32,
    "data": [
        {
            "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 10,
                "learning_rate": 0.0001,
                "epochs": 0.0431941570306258,
                "fim_ratio": null
            },
            "model": "open-mistral-7b",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1721405548,
            "modified_at": 1721405693,
            "training_files": [
                "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
            ],
            "validation_files": [
                "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
            ],
            "fine_tuned_model": "ft:open-mistral-7b:b6e34a5e:20240719:20178c3c",
            "suffix": null,
            "integrations": [],
            "trained_tokens": 1310720,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": 120,
                "cost": 2.6214,
                "cost_currency": "USD",
                "train_tokens_per_step": 131072,
                "train_tokens": 1310720,
                "data_tokens": 30344845,
                "estimated_start_time": null
            }
        },
        {
            "id": "98cbe43b-61e5-47a8-a5fb-57f6d82abc0a",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 10,
                "learning_rate": 0.0001,
                "epochs": 0.0431941570306258,
                "fim_ratio": null
            },
            "model": "open-mistral-7b",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1721405463,
            "modified_at": 1721405603,
            "training_files": [
                "71664e51-eae4-4c5b-9007-2c4586265609"
            ],
            "validation_files": [
                "6c09517c-32d9-465c-8e4b-4496d1401ba0"
            ],
            "fine_tuned_model": "ft:open-mistral-7b:b6e34a5e:20240719:98cbe43b",
            "suffix": null,
            "integrations": [],
            "trained_tokens": 1310720,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": 120,
                "cost": 2.6214,
                "cost_currency": "USD",
                "train_tokens_per_step": 131072,
                "train_tokens": 1310720,
                "data_tokens": 30344845,
                "estimated_start_time": null
            }
        },
        {
            "id": "baf7cb65-5ab6-4cdd-a4c6-a6f90c18cd7b",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 10,
                "learning_rate": 0.0001,
                "epochs": 0.0431941570306258,
                "fim_ratio": null
            },
            "model": "open-mistral-7b",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1721396928,
            "modified_at": 1721397062,
            "training_files": [
                "96d5e16c-d701-455c-8f76-82054d005325"
            ],
            "validation_files": [
                "cfc6dd29-f82e-48c0-8153-59e2313600c8"
            ],
            "fine_tuned_model": "ft:open-mistral-7b:b6e34a5e:20240719:baf7cb65",
            "suffix": null,
            "integrations": [],
            "trained_tokens": 1310720,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": 100,
                "cost": 2.6214,
                "cost_currency": "USD",
                "train_tokens_per_step": 131072,
                "train_tokens": 1310720,
                "data_tokens": 30344845,
                "estimated_start_time": null
            }
        },
        {
            "id": "7d82092d-a827-4943-9361-b321c6a3809c",
            "auto_start": false,
            "hyperparameters": {
                "training_steps": 10,
                "learning_rate": 0.0001,
                "epochs": 0.0431941570306258,
                "fim_ratio": null
            },
            "model": "open-mistral-7b",
            "status": "VALIDATED",
            "job_type": "FT",
            "created_at": 1721396750,
            "modified_at": 1721396751,
            "training_files": [
                "96d5e16c-d701-455c-8f76-82054d005325"
            ],
            "validation_files": [
                "cfc6dd29-f82e-48c0-8153-59e2313600c8"
            ],
            "fine_tuned_model": null,
            "suffix": null,
            "integrations": [],
            "trained_tokens": null,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": 100,
                "cost": 2.6214,
                "cost_currency": "USD",
                "train_tokens_per_step": 131072,
                "train_tokens": 1310720,
                "data_tokens": 30344845,
                "estimated_start_time": null
            }
        },
        {
            "id": "1d69c7fc-fba8-40ad-92d1-3811b708cde1",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 10,
                "learning_rate": 0.0001,
                "epochs": 0.0431941570306258,
                "fim_ratio": null
            },
            "model": "open-mistral-7b",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1721396736,
            "modified_at": 1721396871,
            "training_files": [
                "96d5e16c-d701-455c-8f76-82054d005325"
            ],
            "validation_files": [
                "cfc6dd29-f82e-48c0-8153-59e2313600c8"
            ],
            "fine_tuned_model": "ft:open-mistral-7b:b6e34a5e:20240719:1d69c7fc",
            "suffix": null,
            "integrations": [],
            "trained_tokens": 1310720,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": 100,
                "cost": 2.6214,
                "cost_currency": "USD",
                "train_tokens_per_step": 131072,
                "train_tokens": 1310720,
                "data_tokens": 30344845,
                "estimated_start_time": null
            }
        },
        {
            "id": "64192a7e-b09a-4917-8760-015f90073a7b",
            "auto_start": false,
            "hyperparameters": {
                "training_steps": 10,
                "learning_rate": 0.0001,
                "epochs": 0.0431941570306258,
                "fim_ratio": null
            },
            "model": "open-mistral-7b",
            "status": "VALIDATED",
            "job_type": "FT",
            "created_at": 1721396729,
            "modified_at": 1721396730,
            "training_files": [
                "96d5e16c-d701-455c-8f76-82054d005325"
            ],
            "validation_files": [
                "cfc6dd29-f82e-48c0-8153-59e2313600c8"
            ],
            "fine_tuned_model": null,
            "suffix": null,
            "integrations": [],
            "trained_tokens": null,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": 100,
                "cost": 2.6214,
                "cost_currency": "USD",
                "train_tokens_per_step": 131072,
                "train_tokens": 1310720,
                "data_tokens": 30344845,
                "estimated_start_time": null
            }
        },
        {
            "id": "adc708bd-877a-4201-bef1-16a1f1d93967",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 10,
                "learning_rate": 0.0001,
                "epochs": 0.0431941570306258,
                "fim_ratio": null
            },
            "model": "open-mistral-7b",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1721396580,
            "modified_at": 1721396718,
            "training_files": [
                "96d5e16c-d701-455c-8f76-82054d005325"
            ],
            "validation_files": [
                "cfc6dd29-f82e-48c0-8153-59e2313600c8"
            ],
            "fine_tuned_model": "ft:open-mistral-7b:b6e34a5e:20240719:adc708bd",
            "suffix": null,
            "integrations": [],
            "trained_tokens": 1310720,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": 100,
                "cost": 2.6214,
                "cost_currency": "USD",
                "train_tokens_per_step": 131072,
                "train_tokens": 1310720,
                "data_tokens": 30344845,
                "estimated_start_time": null
            }
        },
        {
            "id": "372926dc-6cea-4198-8234-bd9c1856a2e5",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 10,
                "learning_rate": 0.0001,
                "epochs": 0.0431941570306258,
                "fim_ratio": null
            },
            "model": "open-mistral-7b",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1721396234,
            "modified_at": 1721396369,
            "training_files": [
                "96d5e16c-d701-455c-8f76-82054d005325"
            ],
            "validation_files": [
                "cfc6dd29-f82e-48c0-8153-59e2313600c8"
            ],
            "fine_tuned_model": "ft:open-mistral-7b:b6e34a5e:20240719:372926dc",
            "suffix": null,
            "integrations": [],
            "trained_tokens": 1310720,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": 140,
                "cost": 2.6214,
                "cost_currency": "USD",
                "train_tokens_per_step": 131072,
                "train_tokens": 1310720,
                "data_tokens": 30344845,
                "estimated_start_time": null
            }
        },
        {
            "id": "bdfa52a5-3d66-4c51-bf37-b4ec6e4fa612",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 10,
                "learning_rate": 0.0001,
                "epochs": 0.0431941570306258,
                "fim_ratio": null
            },
            "model": "open-mistral-7b",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1721383368,
            "modified_at": 1721383502,
            "training_files": [
                "962f783d-d38a-46e2-aa7a-8826bf1a42f1"
            ],
            "validation_files": [
                "1d6dbb85-09b6-4962-94f6-ae51f2353733"
            ],
            "fine_tuned_model": "ft:open-mistral-7b:b6e34a5e:20240719:bdfa52a5",
            "suffix": null,
            "integrations": [],
            "trained_tokens": 1310720,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": 210,
                "cost": 2.6214,
                "cost_currency": "USD",
                "train_tokens_per_step": 131072,
                "train_tokens": 1310720,
                "data_tokens": 30344845,
                "estimated_start_time": null
            }
        },
        {
            "id": "ded06fc3-7cf9-4753-a157-c2c3f9c0103b",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 10,
                "learning_rate": 0.0001,
                "epochs": null,
                "fim_ratio": null
            },
            "model": "open-mistral-7b",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1720629436,
            "modified_at": 1720629567,
            "training_files": [
                "2f1e95bb-49cb-4998-9a2c-57a6093390ad"
            ],
            "validation_files": [
                "dfeaa63b-55c5-4850-afd5-61ffebf26782"
            ],
            "fine_tuned_model": "ft:open-mistral-7b:b6e34a5e:20240710:ded06fc3",
            "suffix": null,
            "integrations": [],
            "trained_tokens": 1310720,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": null,
                "cost": null,
                "cost_currency": null,
                "train_tokens_per_step": null,
                "train_tokens": null,
                "data_tokens": null,
                "estimated_start_time": null
            }
        },
        {
            "id": "d1587e39-eb2a-43ac-9f6b-4fa4d0e45c31",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 10,
                "learning_rate": 0.0001,
                "epochs": null,
                "fim_ratio": null
            },
            "model": "open-mistral-7b",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1720629167,
            "modified_at": 1720629288,
            "training_files": [
                "93b01e13-1834-4a8b-b60a-5538d59b2c93"
            ],
            "validation_files": [
                "2e1eb79d-388f-4c03-acfa-09b4bad51a91"
            ],
            "fine_tuned_model": "ft:open-mistral-7b:b6e34a5e:20240710:d1587e39",
            "suffix": null,
            "integrations": [],
            "trained_tokens": 1310720,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": null,
                "cost": null,
                "cost_currency": null,
                "train_tokens_per_step": null,
                "train_tokens": null,
                "data_tokens": null,
                "estimated_start_time": null
            }
        },
        {
            "id": "e89017e4-d038-4056-a869-73ee9e87c79e",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 400,
                "learning_rate": 0.0003,
                "epochs": null,
                "fim_ratio": null
            },
            "model": "mistral-small-latest",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1717576147,
            "modified_at": 1717593291,
            "training_files": [
                "8609ba12-353f-4277-87c8-0e1f7b6f72ce"
            ],
            "validation_files": [
                "0c5f525a-8dce-4c70-abfd-6bff1ec8e0c0"
            ],
            "fine_tuned_model": "ft:mistral-small-latest:b6e34a5e:20240605:e89017e4",
            "suffix": null,
            "integrations": [
                {
                    "project": "test_api",
                    "name": null,
                    "run_name": "economist_style_guide_v8"
                }
            ],
            "trained_tokens": 52428800,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": null,
                "cost": null,
                "cost_currency": null,
                "train_tokens_per_step": null,
                "train_tokens": null,
                "data_tokens": null,
                "estimated_start_time": null
            }
        },
        {
            "id": "3912b6ef-d2da-46b0-946f-56c243b8146f",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 200,
                "learning_rate": 0.0003,
                "epochs": null,
                "fim_ratio": null
            },
            "model": "mistral-small-latest",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1717576026,
            "modified_at": 1717584730,
            "training_files": [
                "8609ba12-353f-4277-87c8-0e1f7b6f72ce"
            ],
            "validation_files": [
                "0c5f525a-8dce-4c70-abfd-6bff1ec8e0c0"
            ],
            "fine_tuned_model": "ft:mistral-small-latest:b6e34a5e:20240605:3912b6ef",
            "suffix": null,
            "integrations": [
                {
                    "project": "test_api",
                    "name": null,
                    "run_name": "economist_style_guide_v7"
                }
            ],
            "trained_tokens": 26214400,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": null,
                "cost": null,
                "cost_currency": null,
                "train_tokens_per_step": null,
                "train_tokens": null,
                "data_tokens": null,
                "estimated_start_time": null
            }
        },
        {
            "id": "7d0c9b8c-d3c7-4890-9788-ea12b917cb46",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 1500,
                "learning_rate": 7.5e-05,
                "epochs": null,
                "fim_ratio": null
            },
            "model": "mistral-small-latest",
            "status": "FAILED",
            "job_type": "FT",
            "created_at": 1717575567,
            "modified_at": 1717575890,
            "training_files": [
                "8609ba12-353f-4277-87c8-0e1f7b6f72ce"
            ],
            "validation_files": [
                "0c5f525a-8dce-4c70-abfd-6bff1ec8e0c0"
            ],
            "fine_tuned_model": null,
            "suffix": null,
            "integrations": [
                {
                    "project": "test_api",
                    "name": null,
                    "run_name": "economist_style_guide_v6"
                }
            ],
            "trained_tokens": null,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": null,
                "cost": null,
                "cost_currency": null,
                "train_tokens_per_step": null,
                "train_tokens": null,
                "data_tokens": null,
                "estimated_start_time": null
            }
        },
        {
            "id": "1d50c69f-4ed5-4888-a05d-cea08e8a1e49",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 800,
                "learning_rate": 7.5e-05,
                "epochs": null,
                "fim_ratio": null
            },
            "model": "mistral-small-latest",
            "status": "FAILED",
            "job_type": "FT",
            "created_at": 1717575373,
            "modified_at": 1717575868,
            "training_files": [
                "8609ba12-353f-4277-87c8-0e1f7b6f72ce"
            ],
            "validation_files": [
                "0c5f525a-8dce-4c70-abfd-6bff1ec8e0c0"
            ],
            "fine_tuned_model": null,
            "suffix": null,
            "integrations": [
                {
                    "project": "test_api",
                    "name": null,
                    "run_name": "economist_style_guide_v5"
                }
            ],
            "trained_tokens": null,
            "repositories": [],
            "metadata": {
                "expected_duration_seconds": null,
                "cost": null,
                "cost_currency": null,
                "train_tokens_per_step": null,
                "train_tokens": null,
                "data_tokens": null,
                "estimated_start_time": null
            }
        },
        {
            "id": "56578b71-9952-445e-a1c4-a77e8970a396",
            "auto_start": true,
            "hyperparameters": {
                "training_steps": 1000,
                "learning_rate": 7.5e-05,
                "epochs": null,
                "fim_ratio": null
            },
            "model": "mistral-small-latest",
            "status": "SUCCESS",
            "job_type": "FT",
            "created_at": 1717513741,
            "modified_at": 1717519351,
            "training_files": [
                "ab8a0a0e-699d-4084-a766-afd681c3e690"
            ],
            "validation_files": [
                "9e48568e-0f51-48d0-bc87-dc45aaba6f4e"
            ],

In [ ]:
# Retrieve a jobs
retrieved_jobs = client.fine_tuning.jobs.get(job_id = created_jobs.id)
pprint(retrieved_jobs)

{
    "id": "20178c3c-d75b-428e-b20d-7d39aa2b7468",
    "auto_start": true,
    "hyperparameters": {
        "training_steps": 10,
        "learning_rate": 0.0001,
        "epochs": 0.0431941570306258,
        "fim_ratio": null
    },
    "model": "open-mistral-7b",
    "status": "SUCCESS",
    "job_type": "FT",
    "created_at": 1721405548,
    "modified_at": 1721405693,
    "training_files": [
        "ec5af16a-77fe-4e14-ad09-47ead2848ce6"
    ],
    "validation_files": [
        "d0c643a2-a57c-4031-bda7-5c9d6c3ec3e4"
    ],
    "fine_tuned_model": "ft:open-mistral-7b:b6e34a5e:20240719:20178c3c",
    "suffix": null,
    "integrations": [],
    "trained_tokens": 1310720,
    "repositories": [],
    "metadata": {
        "expected_duration_seconds": 120,
        "cost": 2.6214,
        "cost_currency": "USD",
        "train_tokens_per_step": 131072,
        "train_tokens": 1310720,
        "data_tokens": 30344845,
        "estimated_start_time": null
    },
    "events": [
        {
            "name": "status-updated",
            "created_at": 1721405693
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405549
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        },
        {
            "name": "status-updated",
            "created_at": 1721405548
        }
    ],
    "checkpoints": [
        {
            "metrics": {
                "train_loss": 0.851776,
                "valid_loss": 0.92623,
                "valid_mean_token_accuracy": 1.900304
            },
            "step_number": 10,
            "created_at": 1721405660
        }
    ]
}

## Use a fine-tuned model

In [ ]:
chat_response = client.chat.complete(
    model = retrieved_jobs.fine_tuned_model,
    messages = [{"role":'user', "content":'What is the best French cheese?'}]
)

In [ ]:
pprint(chat_response)

{
    "id": "1fac96713fd74799922712e34e009f81",
    "object": "chat.completion",
    "model": "ft:open-mistral-7b:b6e34a5e:20240719:20178c3c",
    "usage": {
        "prompt_tokens": 10,
        "completion_tokens": 73,
        "total_tokens": 83
    },
    "created": 1721405725,
    "choices": [
        {
            "index": 0,
            "finish_reason": "stop",
            "message": {
                "content": "There isn't a single \"best\" French cheese as there are hundreds of different types of cheese to choose from, each with its unique taste and texture. Some popular French cheeses include Brie, Camembert, Roquefort, Comt\u00e9, and Ch\u00e8vre. Try different cheeses to find out the one you like best!",
                "tool_calls": null,
                "prefix": false,
                "role": "assistant"
            }
        }
    ]
}

## Integration with Weights and Biases
We can also offer support for integration with Weights & Biases (W&B) to monitor and track various metrics and statistics associated with our fine-tuning jobs. To enable integration with W&B, you will need to create an account with W&B and add your W&B information in the “integrations” section in the job creation request:

In [ ]:
client.fine_tuning.jobs.create(
    model="open-mistral-7b",
    training_files=[{"file_id": ultrachat_chunk_train.id, "weight": 1}],
    validation_files=[ultrachat_chunk_eval.id],
    hyperparameters={"training_steps": 10, "learning_rate": 0.0001},
    integrations=[
        {
            "project": "<value>",
            "api_key": "<value>",
        }
    ]
)